#!/bin/bash

SOURCE_FILE="${1:-Main.cpp}"

g++ -std=gnu++2b -O2 -DONLINE_JUDGE -DATCODER \
-Wall -Wextra \
-mtune=native -march=native \
-fconstexpr-depth=2147483647 -fconstexpr-loop-limit=2147483647 -fconstexpr-ops-limit=2147483647 \
-I./ \
-o a.out $SOURCE_FILE \
-lgmpxx -lgmp